"""foundation and device identity

Revision ID: 614a53a9e2cb
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "614a53a9e2cb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "public_id",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=36),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(create_constraint=True, name="active"), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("public_id", name=op.f("uq_projects_public_id")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "devices",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "device_uuid",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=36),
            nullable=False,
        ),
        sa.Column("project_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "monitoring_enabled",
            sa.Boolean(create_constraint=True, name="monitoring"),
            nullable=False,
        ),
        sa.Column("monitoring_started_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("last_seen_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column(
            "gpu_monitoring_enabled",
            sa.Boolean(create_constraint=True, name="gpu_monitoring"),
            nullable=False,
        ),
        sa.Column("expected_gpu_min_count", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("expected_gpu_uuids", mysql.JSON(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.CheckConstraint(
            "JSON_TYPE(expected_gpu_uuids) = 'ARRAY' AND JSON_LENGTH(expected_gpu_uuids) <= 64",
            name=op.f("ck_devices_gpu_inventory"),
        ),
        sa.CheckConstraint(
            "expected_gpu_min_count BETWEEN 0 AND 64", name=op.f("ck_devices_gpu_count")
        ),
        sa.CheckConstraint(
            "gpu_monitoring_enabled OR (expected_gpu_min_count = 0 AND "
            "JSON_LENGTH(expected_gpu_uuids) = 0)",
            name=op.f("ck_devices_disabled_gpu_policy"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_devices_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("device_uuid", name=op.f("uq_devices_device_uuid")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_devices_project_id"), "devices", ["project_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("project_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("device_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("occurred_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("details", mysql.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_audit_events_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_audit_events_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_audit_events_device_id"), "audit_events", ["device_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "device_credentials",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column(
            "credential_id",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=36),
            nullable=False,
        ),
        sa.Column("device_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("token_digest", sa.BINARY(length=32), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("expires_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("revoked_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("last_used_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_credentials_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_credentials")),
        sa.UniqueConstraint("credential_id", name=op.f("uq_device_credentials_credential_id")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_credentials_device_lifecycle",
        "device_credentials",
        ["device_id", "revoked_at", "expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_credentials_device_lifecycle", table_name="device_credentials")
    op.drop_table("device_credentials")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_device_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_devices_project_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_table("projects")
    # ### end Alembic commands ###
